"""Add new column to events

Revision ID: 4a6f48627535
Revises: bc4b3c154284
Create Date: 2025-12-31 01:55:44.157038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a6f48627535'
down_revision: Union[str, Sequence[str], None] = 'bc4b3c154284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
