"""Add location to events

Revision ID: 7a6eb48b5ac8
Revises: 1700cb6c9430
Create Date: 2025-12-30 23:17:47.419611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6eb48b5ac8'
down_revision: Union[str, Sequence[str], None] = '1700cb6c9430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correspondents', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('correspondents', sa.Column('bio', sa.Text(), nullable=True))
    op.alter_column('correspondents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('correspondents', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_correspondents_email'), table_name='correspondents')
    op.drop_index(op.f('ix_correspondents_name'), table_name='correspondents')
    op.create_unique_constraint(None, 'correspondents', ['email'])
    op.drop_column('correspondents', 'phone_number')
    op.add_column('events', sa.Column('location', sa.String(), nullable=True))
    op.add_column('events', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_constraint(op.f('events_correspondent_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'correspondent_id')
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    op.alter_column('reports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('events', sa.Column('correspondent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_correspondent_id_fkey'), 'events', 'correspondents', ['correspondent_id'], ['id'])
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('events', 'description')
    op.drop_column('events', 'location')
    op.add_column('correspondents', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'correspondents', type_='unique')
    op.create_index(op.f('ix_correspondents_name'), 'correspondents', ['name'], unique=False)
    op.create_index(op.f('ix_correspondents_email'), 'correspondents', ['email'], unique=True)
    op.alter_column('correspondents', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('correspondents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('correspondents', 'bio')
    op.drop_column('correspondents', 'country')
    # ### end Alembic commands ###
