"""add extra_data jsonb column

Revision ID: 7ed3b512e9c8
Revises: 9fbe37aaf3a5
Create Date: 2025-12-31 17:52:58.222449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ed3b512e9c8'
down_revision: Union[str, Sequence[str], None] = '9fbe37aaf3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'extra_data')
    # ### end Alembic commands ###
