"""add phone_number column to correspondents

Revision ID: a39563a1fced
Revises: cd964f2e56fe
Create Date: 2025-12-30 20:48:34.450771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39563a1fced'
down_revision: Union[str, Sequence[str], None] = 'cd964f2e56fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correspondents', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correspondents', 'phone_number')
    # ### end Alembic commands ###
