"""create correspondents table

Revision ID: cd964f2e56fe
Revises: 20fe1b540b56
Create Date: 2025-12-30 20:01:49.153578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd964f2e56fe'
down_revision: Union[str, Sequence[str], None] = '20fe1b540b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correspondents_email'), 'correspondents', ['email'], unique=True)
    op.create_index(op.f('ix_correspondents_id'), 'correspondents', ['id'], unique=False)
    op.create_index(op.f('ix_correspondents_name'), 'correspondents', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correspondents_name'), table_name='correspondents')
    op.drop_index(op.f('ix_correspondents_id'), table_name='correspondents')
    op.drop_index(op.f('ix_correspondents_email'), table_name='correspondents')
    op.drop_table('correspondents')
    # ### end Alembic commands ###
