"""Add category column to events

Revision ID: e1c5c4697564
Revises: 1918d12802db
Create Date: 2025-12-31 17:40:50.996560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c5c4697564'
down_revision: Union[str, Sequence[str], None] = '1918d12802db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(), nullable=True))
    op.drop_index(op.f('idx_event_data_trgm'), table_name='events', postgresql_ops={'(data::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_event_data_trgm'), 'events', [sa.literal_column('(data::text)')], unique=False, postgresql_ops={'(data::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
